# main function
## Function to create a directory
### Function to check if a directory exists

this is a rehular text

---


- task list 1
- task list 2

In [1]:
tempratures =[23, 25, 21, 22, 24]
total = 0
for temp in tempratures:
    total += temp
average = total / len(tempratures)
print("Average temperature:", average)

Average temperature: 23.0


In [2]:
import numpy as np
tempratures = np.array([23, 25, 21, 22, 24])
average = np.mean(tempratures)
print("Average temperature:", average)

Average temperature: 23.0


In [3]:
import numpy as np
arr = np.array([23, 25, 21, 22, 24])
print(arr)

[23 25 21 22 24]


In [4]:
zeroes_array = np.zeros((3))
print(zeroes_array)

[0. 0. 0.]


In [5]:
ones_array = np.ones((4,5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
full_array = np.full((2,3), 7)
print(full_array)

[[7 7 7]
 [7 7 7]]


In [10]:
arr = np.arange(10, 20, 3)
print(arr)

[10 13 16 19]


In [9]:
identy = np.eye(5)
print(identy)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
arr = np.array([23, 25, 21, 22, 24])
print (arr.size)
print (arr.shape)

5
(5,)


In [14]:
array = np.array([[23, 25, 21, 22, 24],
                  [1, 2, 3, 4, 5]])
print(array.ndim)


2


In [16]:
arr =np.array([22, 24, 26, 28, 30])
print(arr.dtype)

int32


In [17]:
arr = np.array([12.6, 14.8, 16.2])
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)

[12 14 16]
int32


In [21]:
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)
print(arr * 2)
print(arr ** 2)
print(arr // 2)
print(arr % 2)



[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[0 1 1 2 2]
[1 0 1 0 1]


In [22]:
arr = np.array([23, 25, 21, 22, 24])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))


115
23.0
21
25
1.4142135623730951


In [ ]:
arr = np.array([23, 25, 21, 22, 24])
print(arr[3])
print(arr[1:4:2])# start:stop:step

22
[25 22]


In [26]:
arr = np.array([23, 25, 21, 22, 24])
print(arr[[0, 2, 4]])  # Accessing elements at indices 0, 2, and 4

[23 21 24]


In [27]:
arr = np.array([23, 25, 21, 22, 24])
print(arr[arr > 22])  # Accessing elements greater than 22

[23 25 24]


In [35]:
arr = np.array([1, 2, 3, 4, 5,6])
reshaped_Arr = arr.reshape((2, 3))
print(reshaped_Arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ravel()) #view
print(arr.flatten())#copy

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [37]:
arr = np.array([23, 25, 21, 22, 24])
print(arr)
new_arr = np.insert(arr, 2, 99)  
print(new_arr)  # Insert 99 at index 2

[23 25 21 22 24]
[23 25 99 21 22 24]


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
new_arr_2d = (np.insert(arr_2d, 1, [99, 88, 29], axis=0))# 0 for rows, 1 for columns & None for both
print(new_arr_2d) 

[[1 2 3]
 [4 5 6]]
[ 1 99 88 29  2  3  4  5  6]


In [48]:
arr = np.array([23, 25, 21, 22, 24])
new_arr = np.append(arr, [26, 27])
print(new_arr)

[23 25 21 22 24 26 27]


In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
new_arr = np.concatenate((arr1, arr2))
print(new_arr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([23, 25, 21, 22, 24])
print(arr)
new_arr = np.delete(arr, 1) # Delete element at index 1 
print(new_arr)  

[23 25 21 22 24]
[23 21 22 24]


In [52]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.vstack((arr1, arr2))) 
print(np.hstack((arr1, arr2))) 

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [53]:
arr = np.array([23, 25, 21, 22, 24, 26])
print(np.split(arr, 2))  # Split into 2 equal parts

[array([23, 25, 21]), array([22, 24, 26])]


In [60]:
arr =np.array([2356, 1234, 5678, 91011])
Discount = 30
print(arr.astype(int) * (1 - Discount / 100))  # Apply a 20% discount to each element

[ 1649.2   863.8  3974.6 63707.7]


In [63]:
arr = np.array([23, 25, 21, np.nan, 22, 24])
print(np.isnan(arr))  # Check for NaN values
cleaned_arr = np.nan_to_num(arr,nan=10)  # Replace NaN with 0
print(cleaned_arr)  # Display the cleaned array


[False False False  True False False]
[23. 25. 21. 10. 22. 24.]


In [65]:
arr = np.array([ 23, 25, np.inf, 21, 22, -np.inf, 24])
print(np.isinf(arr))  # Check for infinite values
cleaned_arr = np.nan_to_num(arr, posinf=10, neginf=-10)  
print(cleaned_arr)  # Replace inf with 10 and -inf with -10


[False False  True False False  True False]
[ 23.  25.  10.  21.  22. -10.  24.]
